I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script
    if text_move == 0:
  File "game/script.rpy", line 6, in <module>
    if text_move == 0:
NameError: name 'text_move' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 6, in script
    if text_move == 0:
  File "/Applications/renpy-7.4.11-sdk/renpy/ast.py", line 1898, in execute
    if renpy.python.py_eval(condition):
  File "/Applications/renpy-7.4.11-sdk/renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-7.4.11-sdk/renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 6, in <module>
    if text_move == 0:
NameError: name 'text_move' is not defined

Darwin-21.4.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
test 1.0
Fri Mar 18 10:22:19 2022
